In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
spam_df = pd.read_csv("/content/mail_data.csv")

In [3]:
spam_df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x == 'spam' else 0 )

In [6]:
spam_df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(spam_df.Message, spam_df.spam, test_size = 0.25)

In [8]:
x_train

2450                            Then she dun believe wat?
2330    Am surfing online store. For offers do you wan...
2910    URGENT! Your Mobile number has been awarded wi...
4850    either way works for me. I am  &lt;#&gt;  year...
3792    Twinks, bears, scallies, skins and jocks are c...
                              ...                        
4266    &lt;DECIMAL&gt; m but its not a common car her...
4361    Night sweet, sleep well! I've just been to see...
4922    Its so common hearin How r u? Wat r u doing? H...
854     AH POOR BABY!HOPE URFEELING BETTERSN LUV! PROB...
4500    SMS SERVICES. for your inclusive text credits,...
Name: Message, Length: 4179, dtype: object

In [9]:
x_train.describe()

count                       4179
unique                      3921
top       Sorry, I'll call later
freq                          22
Name: Message, dtype: object

In [10]:
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [11]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [17]:
email_ham = ["hey wanna meet up for the game?"]
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0])

In [15]:
email_spam = ["reward money click"]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1])

In [19]:
x_test_count = cv.transform(x_test)
model.score(x_test_count,y_test)

0.9856424982053122